// Felt Dashboard Application
// Generated by Felt GIS Workbench

import { Felt } from "https://esm.run/@feltmaps/js-sdk";

let felt;
let currentFilters = {};

async function initializeMap() {
    try {
        // Embed Felt map
        felt = await Felt.embed(
            document.getElementById('map'),
            'qmLUI9Bv6QaeKybiEC9A1uJB',
            {
                uiControls: {
                    showZoomControls: true,
                    showLegend: true,
                    showSearch: false,
                    showShare: true
                }
            }
        );

        console.log('Felt map loaded successfully');

        // Setup event listeners
        setupEventListeners();

        

        // Listen to map interactions
        felt.onPointerMove({
            handler: (event) => handlePointerMove(event)
        });

        felt.onPointerClick({
            handler: (event) => handlePointerClick(event)
        });

    } catch (error) {
        console.error('Failed to initialize map:', error);
        showError('Failed to load map. Please check your connection.');
    }
}



function handlePointerMove(event) {
    // Handle mouse movement over map
    if (event.features && event.features.length > 0) {
        // Show feature info on hover
        const feature = event.features[0];
        updateFeatureInfo(feature);
    }
}

function handlePointerClick(event) {
    // Handle click on map features
    if (event.features && event.features.length > 0) {
        const feature = event.features[0];
        console.log('Clicked feature:', feature);
        showFeatureDetails(feature);
    }
}

function updateFeatureInfo(feature) {
    const infoDiv = document.getElementById('feature-info');
    if (infoDiv) {
        infoDiv.innerHTML = `
            <div class="feature-preview">
                <h3>Hover Info</h3>
                <p>${JSON.stringify(feature.properties, null, 2)}</p>
            </div>
        `;
    }
}

function showFeatureDetails(feature) {
    const infoDiv = document.getElementById('feature-info');
    if (infoDiv) {
        infoDiv.innerHTML = `
            <div class="feature-details">
                <h3>Selected Feature</h3>
                <pre>${JSON.stringify(feature.properties, null, 2)}</pre>
            </div>
        `;
    }
}

function setupEventListeners() {
    // Add any additional event listeners here
    console.log('Event listeners setup complete');
}

function showError(message) {
    const mapContainer = document.getElementById('map');
    mapContainer.innerHTML = `
        <div class="error-message">
            <h2>⚠️ Error</h2>
            <p>${message}</p>
        </div>
    `;
}

// Initialize when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    initializeMap();
});